trigger:
- main

steps:
- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'rjm-aia-connection'
    subscriptionId: 'f885f71a-f10d-470f-a15c-976e4e65c37c'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'rjm-dev-sql-elastic-pool-rg'
    location: 'East US'
    templateLocation: 'URL of the file'
    csmFileLink: 'https://raw.githubusercontent.com/Azure/azure-quickstart-templates/master/101-sql-elastic-pool-create/azuredeploy.json'
    csmParametersFileLink: 'https://raw.githubusercontent.com/Azure/azure-quickstart-templates/master/101-sql-elastic-pool-create/azuredeploy.parameters.json'
    overrideParameters: '-administratorLogin rjmadmin -administratorLoginPassword Password@001 -serverName ${{ serverName }} -elasticPoolName rjmdevsqlelasticpool01 -edition Standard -capacity 100 -databaseCapacityMin 0 -databaseCapacityMax 100'
    deploymentMode: 'Incremental'